services:
  mysql:
    image: mysql:8.0
    container_name: fleximart-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mongo:
    image: mongo:6
    container_name: fleximart-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./part2-nosql:/import

volumes:
  mysql_data:
  mongo_data:
